# NHP-AC remote config
# field with (-) does not support dynamic update
# If the file remote.toml exists, NHP-AC will obtain remote configuration information through the etcd client

# Endpoints: ETCD service access address.
# Key: NHP-AC obtain the configuration information through this key.
# Username: The account of the NHP-Server accessing ETCD.
# Password: The password for NHP-Server to access ETCD.

Endpoints = ["172.16.3.53:2379"]
Key = "openac-1"