# NHP-Server base config
# field with (-) does not support dynamic update

# PrivateKeyBase64 (-): server private key in base64 format.
# DefaultCipherScheme: 0: curve25519, 1: gmsm.
# MIGRATION: Values changed in v2.x. If upgrading: old 0(gmsm)->new 1, old 1(curve)->new 0.
# ListenIp (-): udp listening address.
# ListenPort (-): udp listening port.
# Hostname (-): server domain name.
# LogLevel: 0: silent, 1: error, 2: info, 3: audit, 4: debug, 5: trace.
# DisableAgentValidation: whether for the server to skip the agent's public key validation.
PrivateKeyBase64 = "I9UzYO3skKYmDykz9DRBbV+cEebSw/L5yIvzHI4jz+o="
DefaultCipherScheme = 0
ListenIp = "0.0.0.0"    # empty for ipv4 + ipv6, "0.0.0.0" for ipv4 only
ListenPort = 62206
Hostname = "localhost:62206" # the hostname of NHP-Server
LogLevel = 5
DisableAgentValidation = false

