blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://opennhp.org/docs
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/OpenNHP/opennhp/discussions
    about: Ask questions and discuss ideas
