# list the device peers for the server under [[Devices]] table

# PubKeyBase64: public key for the device in base64 format.
# ExpireTime (epoch timestamp in seconds): peer key validation will fail when it expires.
[[DEs]]
PubKeyBase64 = "CtxNuy7lJ1mJgjqWplcwN8dZhXhSNPhECja1A0OWKa+2wtI7xuB3jPcamogGZGBBfQ4SqnoPGLA7zRQaAotoxg=="
ExpireTime = 1924991999
