# NHP-Agent base config
# field with (-) does not support dynamic update

# PrivateKeyBase64 (-): agent private key in base64 format.
# DefaultCipherScheme: 0: gmsm, 1: curve25519.
# UserId: specify the user id this agent represents.
# OrganizationId: specify the organization id this agent represents.
# LogLevel: 0: silent, 1: error, 2: info, 3: audit, 4: debug, 5: trace.
PrivateKeyBase64 = "O2Ytgu7YraFYqq0iS41vhBNhwb1nPVS9kmPzXxLVNo0="
DefaultCipherScheme = 0
UserId = "agent-0"
OrganizationId = "opennhp.org"
LogLevel = 5
# UserData: a customized user entry for flexibility.
# Its key-value pairs will be send to server along with knock message.
[UserData]
"ExampleKey0" = "StringValue"
"ExampleKey1" = 1
"ExampleKey2" = true
