# list the AC peers for the server under [[ACs]] table

# PubKeyBase64: public key for the AC in base64 format.
# ExpireTime (epoch timestamp in seconds): peer key validation will fail when it expires.
[[ACs]]
PubKeyBase64 = "Fr5jzZDVpNh5m9AcBDMtHGmbCAczHyPegT8IxQ3XAzE="
ExpireTime = 1716345064
