# KGC base config

# MasterPrivateKeyBase64: base64 encoded master private key of KGC
# MasterPublicKeyBase64: base64 encoded master public key of KGC
# DefaultCipherScheme: 0: curve25519, 1: gmsm.
# MIGRATION: Values changed in v2.x. If upgrading: old 0(gmsm)->new 1, old 1(curve)->new 0.
MasterPrivateKeyBase64 = "4KnNzGFzeyhPlf6g/dbIa41jYnZHWM/8T45BwPtEuJQ="
MasterPublicKeyBase64 = "Vh1qLWYyduCXE0xvZOiFbusAtGTL0T30zejCr5FQQBpaw6SvNrnVID/S1Ud/Otr6JZrJFxRVrUdOXPJ3HnZf/Q=="
DefaultCipherScheme = 0
